  sudo: required
  services:
    - docker
  before_install:
    - docker build -t minaeshak/react-test -f ./client/Dockerfile.dev ./client
  script:
    - docker run -e CI=true minaeshak/react-test npm test
  after_success:
    - docker build -t minaeshak/multi-client ./client
    - docker build -t minaeshak/multi-nginx ./nginx
    - docker build -t minaeshak/multi-server ./server
    - docker build -t minaeshak/multi-worker ./worker
    - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push minaeshak/multi-client
    - docker push minaeshak/multi-nginx
    - docker push minaeshak/multi-server
    - docker push minaeshak/multi-worker
  deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "multi-docker"
    env: "Multidocker-env"
    bucket_name: "elasticbeanstalk-us-east-1-305470961975"
    bucket_path: "docker_multi"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY